spring:
 datasource:
   url: jdbc:postgresql://ip:port/test?characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true
   username: postgres
   password: 123456
   driver-class-name: org.postgresql.Driver
   type: com.alibaba.druid.pool.DruidDataSource
   initialSize: 5
   minIdle: 5
   maxActive: 20
   maxWait: 60000
 data:
   elasticsearch:
     cluster-nodes: 10.10.4.16:7886
 application:
   name: demo

mybatis:
 mapper-locations: classpath*:mapper/*Mapper.xml

logging:
  path: ./logs
  file: ./logs/demo/demo.log
  level:
    com : error